---
# -------------------------------------------------------------------
# Triple DC Topology with external Core L3 Device
# 2 Spines, 4 Leaves with 1 Host Each, 2 Borders with "external" WANs
# For use with comparing Configlets (DC1) to Studios (DC2) to AVD (DC3)
# -------------------------------------------------------------------

name: tri-config-dc-topo

mgmt:
  network: clab_mgmt
  bridge: br0
  ipv4-subnet: 10.99.99.0/24
  ipv4-gw: 10.99.99.1

topology:

  kinds:
    ceos:
      image: ceos:4.29.2F
    linux:
      image: mitchv85/ohv-host

  nodes: 

###########################################
# Graphite Node                           #
# Provides Topology Graphing and the      #
# ability to connect to nodes in the      #
# topology via a web/ssh session          #
###########################################

    graphite:
      kind: linux
      image: netreplica/graphite
      mgmt-ipv4: 10.99.99.87
      env:
        GRAPHITE_DEFAULT_TYPE: clab
        GRAPHITE_DEFAULT_TOPO: tri-config-dc-topo
        # CLAB_SSH_CONNECTION: ${SSH_CONNECTION}
      binds:
        # - .:/var/www/localhost/htdocs/clab   <----  This is the old path in docker image netreplica/graphite:webssh2
        - .:/htdocs/clab    # New path required for latest version
      ports:
        - 80:80
      exec:
        # - sh -c 'generate_offline_graph.sh'   # used to generate offline graphs
        - sh -c 'graphite_motd.sh 80'
      labels:
        graph-hide: yes
#########################
# DC1                   #
#########################

#########################
# SPINE                 #
#########################

    DC1-SPINE1:
      kind: ceos
      mgmt-ipv4: 10.99.99.193
      startup-config: ./configs/DC1-SPINE1.cfg
      binds:
        - ./configs/spine-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 3
        graph-icon: switch

    DC1-SPINE2:
      kind: ceos
      mgmt-ipv4: 10.99.99.194
      startup-config: ./configs/DC1-SPINE2.cfg
      binds:
        - ./configs/spine-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 3
        graph-icon: switch

#########################
# LEAF                  #
#########################

    DC1-LEAF1:
      kind: ceos
      mgmt-ipv4: 10.99.99.195
      startup-config: ./configs/DC1-LEAF1.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC1-LEAF2:
      kind: ceos
      mgmt-ipv4: 10.99.99.196
      startup-config: ./configs/DC1-LEAF2.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC1-LEAF3:
      kind: ceos
      mgmt-ipv4: 10.99.99.197
      startup-config: ./configs/DC1-LEAF3.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC1-LEAF4:
      kind: ceos
      mgmt-ipv4: 10.99.99.198
      startup-config: ./configs/DC1-LEAF4.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

#########################
# BORDER                #
#########################

    DC1-BORDER1:
      kind: ceos
      mgmt-ipv4: 10.99.99.199
      startup-config: ./configs/DC1-BORDER1.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC1-BORDER2:
      kind: ceos
      mgmt-ipv4: 10.99.99.200
      startup-config: ./configs/DC1-BORDER2.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

########
# HOST #
########

    DC1-HOST1:
      kind: linux
      image: mitchv85/ohv-host
      mgmt-ipv4: 10.99.99.201
      exec:
        - bash /usr/local/bin/hostnetconfig.sh -i 10.10.10.111/24 -g 10.10.10.1
      labels:
        graph-level: 5
        graph-icon: host

    DC1-HOST2:
      kind: linux
      image: mitchv85/ohv-host
      mgmt-ipv4: 10.99.99.202
      exec:
        - bash /usr/local/bin/hostnetconfig.sh -i 10.20.20.112/24 -g 10.20.20.1
      labels:
        graph-level: 5
        graph-icon: host

#########################
# DC2                   #
#########################

#########################
# SPINE                 #
#########################

    DC2-SPINE1:
      kind: ceos
      mgmt-ipv4: 10.99.99.203
      startup-config: ./configs/DC2-SPINE1.cfg
      binds:
        - ./configs/spine-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 3
        graph-icon: switch

    DC2-SPINE2:
      kind: ceos
      mgmt-ipv4: 10.99.99.204
      startup-config: ./configs/DC2-SPINE2.cfg
      binds:
        - ./configs/spine-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 3
        graph-icon: switch

#########################
# LEAF                  #
#########################

    DC2-LEAF1:
      kind: ceos
      mgmt-ipv4: 10.99.99.205
      startup-config: ./configs/DC2-LEAF1.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC2-LEAF2:
      kind: ceos
      mgmt-ipv4: 10.99.99.206
      startup-config: ./configs/DC2-LEAF2.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC2-LEAF3:
      kind: ceos
      mgmt-ipv4: 10.99.99.207
      startup-config: ./configs/DC2-LEAF3.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC2-LEAF4:
      kind: ceos
      mgmt-ipv4: 10.99.99.208
      startup-config: ./configs/DC2-LEAF4.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

#########################
# BORDER                #
#########################

    DC2-BORDER1:
      kind: ceos
      mgmt-ipv4: 10.99.99.209
      startup-config: ./configs/DC2-BORDER1.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC2-BORDER2:
      kind: ceos
      mgmt-ipv4: 10.99.99.210
      startup-config: ./configs/DC2-BORDER2.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

########
# HOST #
########

    DC2-HOST1:
      kind: linux
      image: mitchv85/ohv-host
      mgmt-ipv4: 10.99.99.211
      exec:
        - bash /usr/local/bin/hostnetconfig.sh -i 10.10.10.121/24 -g 10.10.10.1
      labels:
        graph-level: 5
        graph-icon: host

    DC2-HOST2:
      kind: linux
      image: mitchv85/ohv-host
      mgmt-ipv4: 10.99.99.212
      exec:
        - bash /usr/local/bin/hostnetconfig.sh -i 10.30.30.122/24 -g 10.30.30.1
      labels:
        graph-level: 5
        graph-icon: host

#########################
# DC3                   #
#########################

#########################
# SPINE                 #
#########################

    DC3-SPINE1:
      kind: ceos
      mgmt-ipv4: 10.99.99.213
      startup-config: ./configs/DC3-SPINE1.cfg
      binds:
        - ./configs/spine-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 3
        graph-icon: switch

    DC3-SPINE2:
      kind: ceos
      mgmt-ipv4: 10.99.99.214
      startup-config: ./configs/DC3-SPINE2.cfg
      binds:
        - ./configs/spine-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 3
        graph-icon: switch

#########################
# LEAF                  #
#########################

    DC3-LEAF1:
      kind: ceos
      mgmt-ipv4: 10.99.99.215
      startup-config: ./configs/DC3-LEAF1.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC3-LEAF2:
      kind: ceos
      mgmt-ipv4: 10.99.99.216
      startup-config: ./configs/DC3-LEAF2.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC3-LEAF3:
      kind: ceos
      mgmt-ipv4: 10.99.99.217
      startup-config: ./configs/DC3-LEAF3.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC3-LEAF4:
      kind: ceos
      mgmt-ipv4: 10.99.99.218
      startup-config: ./configs/DC3-LEAF4.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

#########################
# BORDER                #
#########################

    DC3-BORDER1:
      kind: ceos
      mgmt-ipv4: 10.99.99.219
      startup-config: ./configs/DC3-BORDER1.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

    DC3-BORDER2:
      kind: ceos
      mgmt-ipv4: 10.99.99.220
      startup-config: ./configs/DC3-BORDER2.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 4
        graph-icon: switch

########
# HOST #
########

    DC3-HOST1:
      kind: linux
      image: mitchv85/ohv-host
      mgmt-ipv4: 10.99.99.221
      exec:
        - bash /usr/local/bin/hostnetconfig.sh -i 10.10.10.131/24 -g 10.10.10.1
      labels:
        graph-level: 5
        graph-icon: host

    DC3-HOST2:
      kind: linux
      image: mitchv85/ohv-host
      mgmt-ipv4: 10.99.99.222
      exec:
        - bash /usr/local/bin/hostnetconfig.sh -i 10.40.40.132/24 -g 10.40.40.1
      labels:
        graph-level: 5
        graph-icon: host

##################
# WAN Simulation #
##################

    WAN1:
      kind: ceos
      mgmt-ipv4: 10.99.99.223
      startup-config: ./configs/WAN1.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 6
        graph-icon: switch

    WAN2:
      kind: ceos
      mgmt-ipv4: 10.99.99.224
      startup-config: ./configs/WAN2.cfg
      binds:
        - ./configs/leaf-mappings.json:/mnt/flash/EosIntfMapping.json:ro
      labels:
        graph-level: 6
        graph-icon: switch

  links:
######################
# DC1 SPINE1 to LEAF #
######################
    - endpoints: ["DC1-SPINE1:eth1", "DC1-LEAF1:eth3"]
    - endpoints: ["DC1-SPINE1:eth2", "DC1-LEAF2:eth3"]
    - endpoints: ["DC1-SPINE1:eth3", "DC1-LEAF3:eth3"]
    - endpoints: ["DC1-SPINE1:eth4", "DC1-LEAF4:eth3"]
    - endpoints: ["DC1-SPINE1:eth7", "DC1-BORDER1:eth3"]
    - endpoints: ["DC1-SPINE1:eth8", "DC1-BORDER2:eth3"]
######################
# DC1 SPINE2 to LEAF #
######################
    - endpoints: ["DC1-SPINE2:eth1", "DC1-LEAF1:eth4"]
    - endpoints: ["DC1-SPINE2:eth2", "DC1-LEAF2:eth4"]
    - endpoints: ["DC1-SPINE2:eth3", "DC1-LEAF3:eth4"]
    - endpoints: ["DC1-SPINE2:eth4", "DC1-LEAF4:eth4"]
    - endpoints: ["DC1-SPINE2:eth7", "DC1-BORDER1:eth4"]
    - endpoints: ["DC1-SPINE2:eth8", "DC1-BORDER2:eth4"]
####################
# DC1 LEAF to LEAF #
####################
    - endpoints: ["DC1-LEAF1:eth9", "DC1-LEAF2:eth9"]
    - endpoints: ["DC1-LEAF1:eth10", "DC1-LEAF2:eth10"]
    - endpoints: ["DC1-LEAF3:eth9", "DC1-LEAF4:eth9"]
    - endpoints: ["DC1-LEAF3:eth10", "DC1-LEAF4:eth10"]
    - endpoints: ["DC1-BORDER1:eth9", "DC1-BORDER2:eth9"]
    - endpoints: ["DC1-BORDER1:eth10", "DC1-BORDER2:eth10"]
#############
# DC1 HOSTS #
#############
    - endpoints: ["DC1-HOST1:eth1", "DC1-LEAF1:eth1"]
    - endpoints: ["DC1-HOST1:eth2", "DC1-LEAF2:eth1"]
    - endpoints: ["DC1-HOST2:eth1", "DC1-LEAF3:eth1"]
    - endpoints: ["DC1-HOST2:eth2", "DC1-LEAF4:eth1"]
######################
# DC2 SPINE1 to LEAF #
######################
    - endpoints: ["DC2-SPINE1:eth1", "DC2-LEAF1:eth3"]
    - endpoints: ["DC2-SPINE1:eth2", "DC2-LEAF2:eth3"]
    - endpoints: ["DC2-SPINE1:eth3", "DC2-LEAF3:eth3"]
    - endpoints: ["DC2-SPINE1:eth4", "DC2-LEAF4:eth3"]
    - endpoints: ["DC2-SPINE1:eth7", "DC2-BORDER1:eth3"]
    - endpoints: ["DC2-SPINE1:eth8", "DC2-BORDER2:eth3"]
######################
# DC2 SPINE2 to LEAF #
######################
    - endpoints: ["DC2-SPINE2:eth1", "DC2-LEAF1:eth4"]
    - endpoints: ["DC2-SPINE2:eth2", "DC2-LEAF2:eth4"]
    - endpoints: ["DC2-SPINE2:eth3", "DC2-LEAF3:eth4"]
    - endpoints: ["DC2-SPINE2:eth4", "DC2-LEAF4:eth4"]
    - endpoints: ["DC2-SPINE2:eth7", "DC2-BORDER1:eth4"]
    - endpoints: ["DC2-SPINE2:eth8", "DC2-BORDER2:eth4"]
####################
# DC2 LEAF to LEAF #
####################
    - endpoints: ["DC2-LEAF1:eth9", "DC2-LEAF2:eth9"]
    - endpoints: ["DC2-LEAF1:eth10", "DC2-LEAF2:eth10"]
    - endpoints: ["DC2-LEAF3:eth9", "DC2-LEAF4:eth9"]
    - endpoints: ["DC2-LEAF3:eth10", "DC2-LEAF4:eth10"]
    - endpoints: ["DC2-BORDER1:eth9", "DC2-BORDER2:eth9"]
    - endpoints: ["DC2-BORDER1:eth10", "DC2-BORDER2:eth10"]
#############
# DC2 HOSTS #
#############
    - endpoints: ["DC2-HOST1:eth1", "DC2-LEAF1:eth1"]
    - endpoints: ["DC2-HOST1:eth2", "DC2-LEAF2:eth1"]
    - endpoints: ["DC2-HOST2:eth1", "DC2-LEAF3:eth1"]
    - endpoints: ["DC2-HOST2:eth2", "DC2-LEAF4:eth1"]
######################
# DC3 SPINE1 to LEAF #
######################
    - endpoints: ["DC3-SPINE1:eth1", "DC3-LEAF1:eth3"]
    - endpoints: ["DC3-SPINE1:eth2", "DC3-LEAF2:eth3"]
    - endpoints: ["DC3-SPINE1:eth3", "DC3-LEAF3:eth3"]
    - endpoints: ["DC3-SPINE1:eth4", "DC3-LEAF4:eth3"]
    - endpoints: ["DC3-SPINE1:eth7", "DC3-BORDER1:eth3"]
    - endpoints: ["DC3-SPINE1:eth8", "DC3-BORDER2:eth3"]
######################
# DC3 SPINE2 to LEAF #
######################
    - endpoints: ["DC3-SPINE2:eth1", "DC3-LEAF1:eth4"]
    - endpoints: ["DC3-SPINE2:eth2", "DC3-LEAF2:eth4"]
    - endpoints: ["DC3-SPINE2:eth3", "DC3-LEAF3:eth4"]
    - endpoints: ["DC3-SPINE2:eth4", "DC3-LEAF4:eth4"]
    - endpoints: ["DC3-SPINE2:eth7", "DC3-BORDER1:eth4"]
    - endpoints: ["DC3-SPINE2:eth8", "DC3-BORDER2:eth4"]
####################
# DC3 LEAF to LEAF #
####################
    - endpoints: ["DC3-LEAF1:eth9", "DC3-LEAF2:eth9"]
    - endpoints: ["DC3-LEAF1:eth10", "DC3-LEAF2:eth10"]
    - endpoints: ["DC3-LEAF3:eth9", "DC3-LEAF4:eth9"]
    - endpoints: ["DC3-LEAF3:eth10", "DC3-LEAF4:eth10"]
    - endpoints: ["DC3-BORDER1:eth9", "DC3-BORDER2:eth9"]
    - endpoints: ["DC3-BORDER1:eth10", "DC3-BORDER2:eth10"]
#############
# DC3 HOSTS #
#############
    - endpoints: ["DC3-HOST1:eth1", "DC3-LEAF1:eth1"]
    - endpoints: ["DC3-HOST1:eth2", "DC3-LEAF2:eth1"]
    - endpoints: ["DC3-HOST2:eth1", "DC3-LEAF3:eth1"]
    - endpoints: ["DC3-HOST2:eth2", "DC3-LEAF4:eth1"]
###########
# WAN Sim #
###########
    - endpoints: ["WAN1:eth1", "DC1-BORDER1:eth1"]
    - endpoints: ["WAN2:eth1", "DC1-BORDER2:eth1"]
    - endpoints: ["WAN1:eth2", "DC2-BORDER1:eth1"]
    - endpoints: ["WAN2:eth2", "DC2-BORDER2:eth1"]
    - endpoints: ["WAN1:eth3", "DC3-BORDER1:eth1"]
    - endpoints: ["WAN2:eth3", "DC3-BORDER2:eth1"]
#################################################
# DC1 SPINE Peer Links - FOR USE WITH L2LS ONLY #
#################################################
    - endpoints: ["DC1-SPINE1:eth9", "DC1-SPINE2:eth9"]
    - endpoints: ["DC1-SPINE1:eth10", "DC1-SPINE2:eth10"]