---
fabric_name: DC

# Set Design Type to L2ls
design:
  type: l2ls

# Repeat MLAG addressing between pairs
fabric_ip_addressing:
  mlag:
    algorithm: same_subnet

# Spine Switches
l3spine:
  defaults:
    platform: cEOS
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 10.1.0.0/24
    bgp_as: '65432'
    mlag_peer_ipv4_pool: 10.255.255.254/31
    mlag_peer_l3_ipv4_pool: 10.255.255.0/31
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces: [ Ethernet31/1, Ethernet32/1 ]
    mgmt_interface: Management1
  node_groups:
    - group: SPINES
      nodes:
        - name: dcapetz-DC-SPINE1
          id: 1
          mgmt_ip: 10.99.99.2/24
        - name: dcapetz-DC-SPINE2
          id: 2
          mgmt_ip: 10.99.99.3/24

# Leaf Switches
leaf:
  defaults:
    platform: cEOS
    mlag_peer_ipv4_pool: 10.255.255.254/31
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    uplink_switches: [ dcapetz-DC-SPINE1, dcapetz-DC-SPINE2 ]
    uplink_interfaces: [ Ethernet49/1, Ethernet50/1 ]
    mlag_interfaces: [ Ethernet55/1, Ethernet56/1 ]
    mgmt_interface: Management1
  node_groups:
    - group: RACK1
      filter:
        tags: [ "Web" ]
      nodes:
        - name: dcapetz-DC-LEAF1
          id: 1
          mgmt_ip: 10.99.99.4/24
          uplink_switch_interfaces: [ Ethernet1/1, Ethernet1/1 ]
        - name: dcapetz-DC-LEAF2
          id: 2
          mgmt_ip: 10.99.99.5/24
          uplink_switch_interfaces: [ Ethernet2/1, Ethernet2/1 ]
    - group: RACK2
      filter:
        tags: [ "App" ]
      nodes:
        - name: dcapetz-DC-LEAF3
          id: 3
          mgmt_ip: 10.99.99.6/24
          uplink_switch_interfaces: [ Ethernet3/1, Ethernet3/1 ]
        - name: dcapetz-DC-LEAF4
          id: 4
          mgmt_ip: 10.99.99.7/24
          uplink_switch_interfaces: [ Ethernet4/1, Ethernet4/1 ]

##################################################################
# Underlay Routing Protocol - ran on Spines
##################################################################

underlay_routing_protocol: eBGP