###############################################################
# Device Inventory:
# Add new section for each device you want to manage configlets
# Required fields:
#  Key:
#    name:
#    configlets:
#    parentContainerName:
#
# Note: You do no need to list configlets that are inherited
#       from a container the device is attached to.  CVP will
#       merge them together
###############################################################

CVP_DEVICES:
  - fqdn: DC2-SW1.thielnet.com
    parentContainerName: DC2
    configlets:
      - DC2_SW1-BASE
  - fqdn: DC2-SW2.thielnet.com
    parentContainerName: DC2
    configlets:
      - DC2_SW2-BASE