###############################################################
# Device Inventory:
# Add new section for each device you want to manage configlets
# Required fields:
#  Key:
#    name:
#    configlets:
#    parentContainerName:
#
# Note: You do no need to list configlets that are inherited
#       from a container the device is attached to.  CVP will
#       merge them together
###############################################################

CVP_DEVICES:
  - fqdn: CO-1
    parentContainerName: Home
    configlets:
      - ANSIBLE_CO-1-BASE
      - ANSIBLE_CO-1-LOCAL-CONFIG
      - ANSIBLE_CO-1-ROUTING
  - fqdn: CO-2
    parentContainerName: Home
    configlets:
      - ANSIBLE_CO-2-BASE
      - ANSIBLE_CO-2-LOCAL-CONFIG
      - ANSIBLE_CO-2-ROUTING
  - fqdn: CO-3
    parentContainerName: Home
    configlets:
      - ANSIBLE_CO-3-BASE
      - ANSIBLE_CO-3-LOCAL-CONFIG
      - ANSIBLE_CO-3-ROUTING
  - fqdn: CO-4
    parentContainerName: Home
    configlets:
      - ANSIBLE_CO-4-BASE
      - ANSIBLE_CO-4-LOCAL-CONFIG
      - ANSIBLE_CO-4-ROUTING
  - fqdn: CO-1-ACCESS
    parentContainerName: CO-1
    configlets:
      - ANSIBLE_CO-1-ACCESS-BASE
      - ANSIBLE_CO-1-ACCESS-CONFIG
  - fqdn: CO-2-ACCESS
    parentContainerName: CO-2
    configlets:
      - ANSIBLE_CO-2-ACCESS-BASE
      - ANSIBLE_CO-2-ACCESS-CONFIG
  - fqdn: CO-3-ACCESS
    parentContainerName: CO-3
    configlets:
      - ANSIBLE_CO-3-ACCESS-BASE
      - ANSIBLE_CO-3-ACCESS-CONFIG
  - fqdn: CO-4-ACCESS
    parentContainerName: CO-4
    configlets:
      - ANSIBLE_CO-4-ACCESS-BASE
      - ANSIBLE_CO-4-ACCESS-CONFIG
  - fqdn: CO-2-DIA
    parentContainerName: CO-2
    configlets:
      - ANSIBLE_CO-2-DIA-BASE
      - ANSIBLE_CO-2-DIA-CONFIG
  - fqdn: CO-3-DIA
    parentContainerName: CO-3
    configlets:
      - ANSIBLE_CO-3-DIA-BASE
      - ANSIBLE_CO-3-DIA-CONFIG