---
fabric_name: DC

# Set Design Type to Layer 3 Leaf-Spine with EVPN Overlay
design:
  type: l3ls-evpn

# Set IPv4 Underlay Routing and EVPN Overlay Routing to use eBGP
#underlay_routing_protocol: ebgp
#overlay_routing_protocol: ebgp

# Repeat MLAG addressing between pairs
fabric_ip_addressing:
  mlag:
    algorithm: same_subnet

# Spine Switches
l3spine:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 10.1.0.0/24
    bgp_as: '65432'
    mgmt_interface: Management1
  nodes:
    - name: dcapetz-DC-SPINE1
      id: 1
      mgmt_ip: 10.99.99.2/24
    - name: dcapetz-DC-SPINE2
      id: 2
      mgmt_ip: 10.99.99.3/24

# Leaf Switches
l3leaf:
  defaults:
    platform: cEOS
    mlag_peer_ipv4_pool: 10.255.255.254/31
    spanning_tree_priority: 4096 
    spanning_tree_mode: mstp
    loopback_ipv4_pool: 10.1.1.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.1.255.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    uplink_switches: [ dcapetz-DC-SPINE1, dcapetz-DC-SPINE2 ]
    uplink_interfaces: [ Ethernet49/1, Ethernet50/1 ]
    uplink_ipv4_pool: 10.0.0.0/22
    mlag_interfaces: [ Ethernet55/1, Ethernet56/1 ]
    mlag_peer_ipv4_pool: 10.255.255.254/31
    mlag_peer_l3_ipv4_pool: 10.254.254.0/24
    mgmt_interface: Management1
  node_groups:
    - group: RACK1
      nodes:
        - name: dcapetz-DC-LEAF1
          id: 1
          mgmt_ip: 10.99.99.4/24
          uplink_switch_interfaces: [ Ethernet1/1, Ethernet1/1 ]
        - name: dcapetz-DC-LEAF2
          id: 2
          mgmt_ip: 10.99.99.5/24
          uplink_switch_interfaces: [ Ethernet2/1, Ethernet2/1 ]
    - group: RACK2
      nodes:
        - name: dcapetz-DC-LEAF3
          id: 3
          mgmt_ip: 10.99.99.6/24
          uplink_switch_interfaces: [ Ethernet3/1, Ethernet3/1 ]
        - name: dcapetz-DC-LEAF4
          id: 4
          mgmt_ip: 10.99.99.7/24
          uplink_switch_interfaces: [ Ethernet4/1, Ethernet4/1 ]
    - group: BORDER
      nodes:
        - name: dcapetz-DC-BORDER1
          id: 31
          mgmt_ip: 10.99.99.10/24
          uplink_switch_interfaces: [ Ethernet3/1, Ethernet3/1 ]
        - name: dcapetz-DC-BORDER2
          id: 32
          mgmt_ip: 10.99.99.11/24
          uplink_switch_interfaces: [ Ethernet4/1, Ethernet4/1 ]