---
port_profiles:

  - profile: VLAN10
    mode: "access"
    vlans: "10"
    spanning_tree_portfast: edge
  - profile: VLAN20
    mode: "access"
    vlans: "20"
    spanning_tree_portfast: edge

###########################################################
# ---------------- Endpoint Connectivity ---------------- #
###########################################################

servers:

# # --------------------------------------------------------#
# # Site1 RACK1 Endpoints
# # --------------------------------------------------------#

  - name: DC-HOST1                                                      # Server name
    rack: RACK1                                                         # Informational RACK (optional)
    adapters:
      - endpoint_ports: [ eth1, eth2 ]                                  # Server port to connect (optional)
        switch_ports: [ Ethernet1, Ethernet1 ]                          # Switch port to connect server (required)
        switches: [ dcapetz-DC-LEAF1, dcapetz-DC-LEAF2 ]                # Switch to connect server (required)
        profile: VLAN10                                                 # Port profile to apply (required)
        port_channel:
          mode: active

# # --------------------------------------------------------#
# # Site1 RACK2 Endpoints
# # --------------------------------------------------------#

  - name: DC-HOST2                                                      # Server name
    rack: RACK2                                                         # Informational RACK (optional)
    adapters:
      - endpoint_ports: [ eth1, eth2 ]                                  # Server port to connect (optional)
        switch_ports: [ Ethernet1, Ethernet1 ]                          # Switch port to connect server (required)
        switches: [ dcapetz-DC-LEAF3, dcapetz-DC-LEAF4 ]                # Switch to connect server (required)
        profile: VLAN20                                                 # Port profile to apply (required)
        port_channel:
          mode: active