---
# ansible-playbook create_base_configs.yml
- name: Create Base Configlets from CSV data
  gather_facts: no
  hosts: localhost

  vars_files:
    - ../datafiles/tenants.yml
    - ../datafiles/mlags.yml

  tasks:

  - name: "Reading in CSV file"
    read_csv:
      path: ../datafiles/devices.csv
    register: switches

  - name: Create Base Config for each device in CSV File
    template: src=../templates/base-cfg.j2 dest=../cvp_configlets/{{ switch.hostname }}-BASE.txt
    loop: "{{ switches.list }}"
    loop_control:
      loop_var: switch

  - name: Create Common VRFs for Leafs
    when: item.hostname is match(".*-1")
    template: src=../templates/vrfs-cfg.j2 dest=../cvp_configlets/{{ item.hostname | regex_replace('-1$','') }}-VRFs.txt
    with_items: "{{ switches.list }}"

  - name: Create Common VLANs for Leafs
    when: 
      - item.hostname is match(".*-1")
      - item.compute == "yes"
    template: src=../templates/vlans-cfg.j2 dest=../cvp_configlets/{{ item.hostname | regex_replace('-1$','') }}-VLANs.txt
    with_items: "{{ switches.list }}"

  - name: Configure MLAG Interfaces
    when: 
      - item.hostname is match(".*-1")
      - item.compute == "yes"
    template: src=../templates/mlags-cfg.j2 dest=../cvp_configlets/{{ item.hostname | regex_replace('-1$','') }}-MLAGs.txt
    with_items: "{{ switches.list }}"

  - name: Configure Orphan Interfaces
    when: item.compute == "yes"
    template: src=../templates/orphans-cfg.j2 dest=../cvp_configlets/{{ item.hostname }}-Switchports.txt
    with_items: "{{ switches.list }}"