---
# ansible-playbook generate_configs.yml
- name: Create Base Configlets from CSV or YAML data
  gather_facts: false
  hosts: localhost

  vars_files:
    - ../datafiles/tenants.yml
    - ../datafiles/mlags.yml
    - ../datafiles/orphans.yml
    - ../datafiles/devices.yml

  tasks:

#  - name: "Reading in CSV file"
#    tags: [ base, mgmt ]
#    read_csv:
#      path: ../datafiles/devices.csv
#    register: switches

#  - name: Create Base Config for each device in CSV File
#    tags: [ base ]
#    template: src=../templates/ceos-base-cfg.j2 dest=../cvp_configlets/{{ switch.hostname }}.cfg
#    loop: "{{ switches.list }}"
#    loop_control:
#      loop_var: switch

  - name: Create MGMT Config for each device in YAML File
    tags: [ base ]
    template: src=../templates/ceos-base-cfg-yml.j2 dest=../cvp_configlets/{{ item.key }}.cfg
    loop: "{{ SWITCHES | dict2items }}"

#  - name: Create MGMT Config for each device in CSV File
#    tags: [ mgmt ]
#    template: src=../templates/ceos-mgmt-cfg.j2 dest=../cvp_configlets/{{ switch.hostname }}-MGMT-TEST.txt
#    loop: "{{ switches.list }}"
#    loop_control:
#      loop_var: switch

  - name: Create Base MGMT Configlet for each device in YAML File
    tags: [ mgmt ]
    template: src=../templates/ceos-mgmt-cfg-yml.j2 dest=../cvp_configlets/{{ item.key }}-MGMT.txt
    loop: "{{ SWITCHES | dict2items }}"
  
#  - name: Create Common VRFs for Leafs
#    when: item.hostname is match(".*-1")
#    template: src=../templates/vrfs-cfg.j2 dest=../cvp_configlets/{{ item.hostname | regex_replace('-1$','') }}-VRFs.txt
#    with_items: "{{ switches.list }}"
#
#  - name: Create Common VLANs for Leafs
#    when: 
#      - item.hostname is match(".*-1")
#      - item.compute == "yes"
#    template: src=../templates/vlans-cfg.j2 dest=../cvp_configlets/{{ item.hostname | regex_replace('-1$','') }}-VLANs.txt
#    with_items: "{{ switches.list }}"

#  - name: Configure MLAG Interfaces
#    when: 
#      - item.hostname is match(".*LEAF01|.*LEAF03")
#      - item.compute == "yes"
#    template: src=../templates/mlags-cfg.j2 dest=../cvp_configlets/{{ item.hostname | regex_replace('-LEAF0','-Pod-') }}-MLAGs.txt
#    with_items: "{{ switches.list }}"
#
#  - name: Configure Orphan Interfaces
#    when: item.compute == "yes"
#    template: src=../templates/orphans-cfg.j2 dest=../cvp_configlets/{{ item.hostname }}-orphan-ports.txt
#    with_items: "{{ switches.list }}"